domain: 96boards.org/pinout
analytics_id:
base_url: /pinout/
resource_url: /pinout/resources/
url_suffix:
urls:
  GND: ground
featured:
- d3-camera-mezzanine
- grove-seeed-sensor-mezzanine
- aero-core-2
- ethernet-mezzanine
overlays:
- ground
- i2c
- spi
- uart
- arrow-link-sprite-mezzanine-kit
- aero-core-2
- d3-camera-mezzanine
- grove-seeed-sensor-mezzanine
- ethernet-mezzanine
- arrow-audio-mezzanine
- mipi-adapter-mezzanine-aistarvision
- stm32-sensor-mezzanine-board
- uart-serial-mezzanine
- neon-key-mezzanine
- link-sprite-lora-mezzanine
- neonkey_mezzanine
